
services:
  - type: web
    name: aiagent-recommendations
    env: python
    repo: https://github.com/Zanarepo/Recommendations
    branch: main
    pythonVersion: 3.9.18
    buildCommand: pip install --upgrade pip && pip install setuptools>=65.5.0 && pip install -r requirements.txt
    startCommand: gunicorn -w 1 --timeout 60 -b 0.0.0.0:$PORT recommendations:app
    envVars:
      - key: SUPABASE_URL
        value: https://qffcyvjugmtojpdgqriv.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000